---
- name: development environment
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - name: update system
    shell: apt-get update && apt-get upgrade -y
  - name: install window manager
    shell: apt-get install -y i3 suckless-tools compton xinit
  - name: install basic tools
    shell: apt-get install -y zsh tmux git ranger neovim qutebrowser terminator && sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  - name: install docker
    become: no
    shell: curl -sSL https://get.docker.com | sh
  - name: get repos
    become: no
    git:
      repo: https://github.com/Farewell-Solenya/side
      dest: ~/sIDE
  - name: build sIDE
    shell: echo build side
  - name: set up dotfiles
    shell: echo get dotfiles
